#!/bin/sh

dir=`dirname $0`

find "${dir}" -name "test_*" -type f | while read t
do
  log=$("${dir}/run_test" "${t}" 2>&1)
  if [ $? != 0 ]; then
    echo "${t} failed"
    echo "${log}"
  fi
done

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
