--- !ditz.rubyforge.org,2008-03-06/project 
name: run
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: doc
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.0
  status: :released
  release_time: 2012-05-03 07:10:56.329866 Z
  log_events: 
  - - 2011-11-06 13:55:58.636003 Z
    - Tomohiko Sumi <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - First release.
  - - 2012-05-03 07:10:56.329898 Z
    - Tomohiko Sumi <SumiTomohiko@neko-daisuki.ddo.jp>
    - released
    - ""
